ESRI-99 unit tests
cyclomedia/streetsmart-dotnet pull request #52
Opened 2024-08-16 09:05 UTC by AleksaMilivojevicCycloMedia

ESRI-99 unit tests

2024-08-26 15:18 UTC, bervacanin-cy requested changes
Few improvements possible.

2024-08-26 15:18 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/SvgParameterCollectionTests.cs
> +    int red = (argb >> 16) & 0xFF;
Simple transformation, like this ColorTranslator.FromHtml(hex) can be used here.

2024-08-26 15:18 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +      var funcName = GetFunctionNameFromScript(s);
This is not needed. We are comparing value with value defined in test class.

2024-08-26 15:18 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +    Mock.Verify();
Are we sure this line is verifying something? When will this fail?

2024-08-26 15:18 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +  public void IsValidJson_WhitespaceInput_ReturnsFalse()
I think this can be moved to test IsValidJson_ValidatesJsonStringsCorrectly, since we already have lot of InlineData defined in that test.

2024-08-26 15:18 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +  public void IsValidJson_InvalidJson_ReturnsFalse()
I think this can be moved to test IsValidJson_ValidatesJsonStringsCorrectly, since we already have lot of InlineData defined in that test.

2024-08-26 15:18 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +  public void IsValidJson_ValidJsonWithComplexStructure_ReturnsTrue()
I think this can be moved to test IsValidJson_ValidatesJsonStringsCorrectly, since we already have lot of InlineData defined in that test.

2024-08-26 15:18 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +  public void IsValidJson_InvalidJsonWithUndefined_ReturnsFalse()
I think this can be moved to test IsValidJson_ValidatesJsonStringsCorrectly, since we already have lot of InlineData defined in that test.

2024-08-26 15:18 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +  public void IsValidJson_JsonWithNullValues_ReturnsTrue()
I think this can be moved to test IsValidJson_ValidatesJsonStringsCorrectly, since we already have lot of InlineData defined in that test.

2024-08-28 07:04 UTC, bervacanin-cy requested changes
Some improvements in coverage are possible.

2024-08-28 07:04 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +    _browserMock.Setup(x => x.ExecuteScriptAsync(It.IsAny<string>())).Callback(() => _viewer.OnResult(new { id = 4 }, "AddOverlay1")).Verifiable(Times.Once);
Is it OK to have It.IsAny string as input parameter? Do we need to validate input parameter format here?

2024-08-28 07:04 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +  public async Task AddOverlay_NullOverlay_ThrowsStreetSmartJsonException()
I think we are missing GeoJson null test for full coverage of the "AddOverlay" method.

2024-08-28 07:04 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +    var result = await _viewer.CallJsGetScriptAsync("skripta", "CallJsGetScriptAsync");
Please, use English language in the source code.

2024-08-28 07:04 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +    var result = await _viewer.CallJsGetScriptAsync("skripta", "CallJsGetScriptAsync");
Should we validate there are no calls to "ExecuteScriptAsync" in this test?

2024-08-28 07:04 UTC, bervacanin-cy commented on StreetSmartAPI/StreetSmart.WPF.Tests/StreetSmartAPITests.cs
> +    var result = await _viewer.CallJsGetScriptAsync("skripta", "CallJsGetScriptAsync");
Should we validate there are no calls to "ExecuteScriptAsync" in this test?

2024-08-28 09:34 UTC, martin-sven-kovacic-valcon requested changes

2024-08-28 09:34 UTC, martin-sven-kovacic-valcon commented on StreetSmartAPI/StreetSmart.WPF.Tests/SvgParameterCollectionTests.cs
> +  public void GetStrokeObject_RandomColor_NullWidthAndOpacity_ReturnsExpectedResult()
add real randomization to the this random test

2024-08-28 09:34 UTC, martin-sven-kovacic-valcon commented on StreetSmartAPI/StreetSmart.WPF.Tests/SvgParameterCollectionTests.cs
> +  public void GetFillObject_AllZeroColor_NullOpacity_ReturnsExpectedResult()
convert all this facts to one theory

2024-08-28 09:38 UTC, bervacanin-cy approved these changes

2024-08-28 13:23 UTC, martin-sven-kovacic-valcon approved these changes

2024-08-28 13:37 UTC, merged